AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema*.rb"
    - "db/seeds.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "bin/*"
    - "config/**/*"
    - "test/**/*"
    - "Gemfile"
    - "Rakefile"
    - "config.ru"
